[Remote Rule]
https://anfeng-crystal.github.io/proxy-rules-dist/loon/OpenAI/OpenAI.list, policy=OpenAI, tag=OpenAI, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Homebrew/Homebrew.list, policy=Homebrew, tag=Homebrew, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/GitHub/GitHub.list, policy=GitHub, tag=GitHub, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Apple/Apple.list, policy=Apple, tag=Apple, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Google/Google.list, policy=Google, tag=Google, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Telegram/Telegram.list, policy=Telegram, tag=Telegram, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/GlobalMedia/GlobalMedia.list, policy=GlobalMedia, tag=GlobalMedia, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Global/Global.list, policy=Global, tag=Global, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Direct/Direct.list, policy=DIRECT, tag=Direct, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/China/China.list, policy=DIRECT, tag=China, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Advertising/Advertising.list, policy=REJECT, tag=Advertising, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Privacy/Privacy.list, policy=REJECT, tag=Privacy, enabled=true
