[Remote Rule]
https://anfeng-crystal.github.io/proxy-rules-dist/loon/AI/AI.lsr, policy=🤖 AI, tag=AI, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/YouTube/YouTube.lsr, policy=📺 YouTube, tag=YouTube, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Netflix/Netflix.lsr, policy=🎬 Netflix, tag=Netflix, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/DisneyPlus/DisneyPlus.lsr, policy=🏰 DisneyPlus, tag=DisneyPlus, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Google/Google.lsr, policy=🇬 Google, tag=Google, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/GitHub/GitHub.lsr, policy=🐙 GitHub, tag=GitHub, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Microsoft/Microsoft.lsr, policy=🪟 Microsoft, tag=Microsoft, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Apple/Apple.lsr, policy=🍎 Apple, tag=Apple, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Telegram/Telegram.lsr, policy=✈️ Telegram, tag=Telegram, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/PayPal/PayPal.lsr, policy=💳 PayPal, tag=PayPal, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/GlobalMedia/GlobalMedia.lsr, policy=🎞️ 境外流媒体, tag=GlobalMedia, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/GlobalSites/GlobalSites.lsr, policy=🌐 境外网站, tag=GlobalSites, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Domestic/Domestic.lsr, policy=🇨🇳 国内应用, tag=Domestic, enabled=true
