[Remote Rule]
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Domestic/Domestic.list, policy=国内应用, tag=Domestic, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/NetworkTest/NetworkTest.list, policy=网络检测, tag=NetworkTest, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/AI/AI.list, policy=AI, tag=AI, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Dev/Dev.list, policy=Dev, tag=Dev, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Payment/Payment.list, policy=Payment, tag=Payment, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Game/Game.list, policy=Game, tag=Game, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Telegram/Telegram.list, policy=Telegram, tag=Telegram, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/YouTube/YouTube.list, policy=YouTube, tag=YouTube, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Netflix/Netflix.list, policy=Netflix, tag=Netflix, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/DisneyPlus/DisneyPlus.list, policy=DisneyPlus, tag=DisneyPlus, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Spotify/Spotify.list, policy=Spotify, tag=Spotify, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/TikTok/TikTok.list, policy=TikTok, tag=TikTok, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Twitter/Twitter.list, policy=Twitter, tag=Twitter, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Facebook/Facebook.list, policy=Facebook, tag=Facebook, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Instagram/Instagram.list, policy=Instagram, tag=Instagram, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Apple/Apple.list, policy=Apple, tag=Apple, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Microsoft/Microsoft.list, policy=Microsoft, tag=Microsoft, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Google/Google.list, policy=Google, tag=Google, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/GitHub/GitHub.list, policy=GitHub, tag=GitHub, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/GlobalSites/GlobalSites.list, policy=境外网站, tag=GlobalSites, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Ads/Ads.list, policy=Ads, tag=Ads, enabled=true
