[Remote Rule]
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Domestic/Domestic.lsr, policy=国内应用, tag=Domestic, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/NetworkTest/NetworkTest.lsr, policy=网络检测, tag=NetworkTest, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/SpeedTest/SpeedTest.lsr, policy=SpeedTest, tag=SpeedTest, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/AI/AI.lsr, policy=AI, tag=AI, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Dev/Dev.lsr, policy=Dev, tag=Dev, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Payment/Payment.lsr, policy=Payment, tag=Payment, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Game/Game.lsr, policy=Game, tag=Game, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Telegram/Telegram.lsr, policy=Telegram, tag=Telegram, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/YouTube/YouTube.lsr, policy=YouTube, tag=YouTube, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Netflix/Netflix.lsr, policy=Netflix, tag=Netflix, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/DisneyPlus/DisneyPlus.lsr, policy=DisneyPlus, tag=DisneyPlus, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Spotify/Spotify.lsr, policy=Spotify, tag=Spotify, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/TikTok/TikTok.lsr, policy=TikTok, tag=TikTok, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Twitter/Twitter.lsr, policy=Twitter, tag=Twitter, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Facebook/Facebook.lsr, policy=Facebook, tag=Facebook, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Instagram/Instagram.lsr, policy=Instagram, tag=Instagram, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Apple/Apple.lsr, policy=Apple, tag=Apple, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Microsoft/Microsoft.lsr, policy=Microsoft, tag=Microsoft, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Google/Google.lsr, policy=Google, tag=Google, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/GitHub/GitHub.lsr, policy=GitHub, tag=GitHub, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/GlobalSites/GlobalSites.lsr, policy=境外网站, tag=GlobalSites, enabled=true
https://anfeng-crystal.github.io/proxy-rules-dist/loon/Ads/Ads.lsr, policy=Ads, tag=Ads, enabled=true
